/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    SiteHeader: typeof import('./src/components/SiteHeader.vue')['default']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
  }
}
