/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElTag: typeof import('element-plus/es')['ElTag']
    Item: typeof import('./../src/components/artical-list/item.vue')['default']
    List: typeof import('./../src/components/artical-list/list.vue')['default']
    LiveComponent: typeof import('./../src/components/LiveComponent.vue')['default']
    SiteHeader: typeof import('./../src/components/SiteHeader.vue')['default']
    TestComponent: typeof import('./../src/components/TestComponent.vue')['default']
  }
}
